import Header from "@/components/header/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { AppProvider } from "@/context/context";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={roboto.className}>
          <Header />
          <div className=" bg-slate-50 min-h-screen">{children}</div>
          <Footer />
        </body>
      </html>
    </AppProvider>
  );
}
